### ISSUE TITLE
Visualization Code

### ISSUE THREAD

**Issue by vhvkhoa** [huangjh-pub/synorim#2]
Thank you very much for your high impact work. The results are very impressive.
I would like to ask for the visualization code or how to visualize input point clouds and the registered point cloud at output ?

**Comment by tolgabirdal** [comment]
We visualize the point clouds using a custom Blender script, which we have not released. If MeshLab is not enough for you, I would direct you to: https://github.com/tolgabirdal/Mitsuba2PointCloudRenderer. This has similar render quality.

Maybe @heiwang1997 also has something to add here.

**Comment by vhvkhoa** [comment]
Thank you so much for the clarification. 
But I think the current source code only supports training and evaluating on pre-processed dataset in .npz format.

Can I ask you for some instruction to do inference with SyNoRiM on the input point clouds to generate registered point cloud, then view inputs and output ?

**Comment by heiwang1997** [comment]
Hi @vhvkhoa, thanks for your interest in our work. I have just pushed a modification to the evaluation script. If you run it with an additional `--visualize` flag, you will then be able to view all pairwise scene flows inferred by our method.
The visualization is based on open3d -- you can install it via pip.

Thanks.
