### ISSUE TITLE
Code for preprocessing the DT4D dataset.

### ISSUE THREAD

**Issue by puhuajiang** [huangjh-pub/synorim#3]
Hi, thank you for your wonderful work and the code.!

I noticed that for DT4D data, you guys transform the original data to a fixed point cloud data(with length of 8192). Recently I want to do it by myself. So, could you offer the preprocessing code of the DT4D dataset?

Thank you!

**Comment by heiwang1997** [comment]
Hi. Thanks for your interest in our work. The data processing part is unfortunately not part of our open source release due to the licensing issues. Please drop me an email and I could send the script to you.

**Comment by puhuajiang** [comment]
Okay, thank you for your response
