### ISSUE TITLE
KeyError: 'flow_masks is not a file in the archive'

### ISSUE THREAD

**Issue by ElahehOmidkhoda** [huangjh-pub/synorim#5]
Hi, thank you for your excellent work. 
I want to run synorim project via jittor, but when execute "python train.py configs/train_desc.yaml" command, I got this error
raise KeyError("%s is not a file in the archive" % key)
KeyError: 'flow_masks is not a file in the archive'
could you please guide me?

**Comment by heiwang1997** [comment]
Thanks for your interest in our work! 
This is weird though. Does the pytorch version also give you the same error?

Best,
Jiahui

**Comment by ElahehOmidkhoda** [comment]
I don't run pytorch version because of Minkowski Engine doesn't build on my system. Can I ask your hardware specification to build Minkowski Engine?
My hardware specification are:
Ubuntu 22.04
GPU: NVIDIA GEFORCE GTX 960M
RAM: 12G
Driver Version: 515.65.01
Cuda: 11.7
But I guess, this error will occured in pytorch version too, because npz files in "dataset/mpc-cape/data/" contain just "pcs.npy" and "flows.npy"!!

**Comment by heiwang1997** [comment]
Jittor version does not use sparse conv but PointNet++ instead so you will not be able to fully reproduce our results in the paper, unfortunately.
My suggestion is still to try building MinkowskiEngine. May I know what is the error when you build ME?
My hardware is:
Ubuntu 20.04
GPU: nvidia gtx 3090
RAM: 128g
Driver version: 510.85.02
Cuda: 11.6

The pytorch version runs with no problem on my side btw :)

**Comment by ElahehOmidkhoda** [comment]
Thanks for your quick and kind replies, finally I could build ME on my system, and pytorch version runs with no problem :)
One more question about testing on my own data.
I have 8 pointcloud that captured from different side of body, is it possible to construct full 3d body model with this project? 
If I save 8 pointcloud in numpy array (.npy), is it correct?

**Comment by heiwang1997** [comment]
Hey @elahehomidkhoda 

That's correct! I would recommend putting the body sides into world space before doing our non-rigid registration. It would be good if there could be some overlaps between these scans :)
