### ISSUE TITLE
数据集下载

### ISSUE THREAD

**Issue by chenyifanthu** [huangjh-pub/synorim#8]
您好，请问4个数据集有没有国内的下载链接。Google Drive会因为网络不稳定以及限流的原因而下载失败，谢谢。

**Comment by heiwang1997** [comment]
我晚上给你传个清华网盘？

**Comment by chenyifanthu** [comment]
可以，谢谢~

**Comment by heiwang1997** [comment]
https://cloud.tsinghua.edu.cn/d/ca41871a98eb4ee3a990/

单个zip文件比较大，学校网盘有5g的限制，所以我把大一点的数据集分割成小块了，请查收~
