### ISSUE TITLE
mpc-dt4d dataset not in the google drive link?

### ISSUE THREAD

**Issue by 1939938853** [huangjh-pub/synorim#9]
Hello,

It is very interesting to try Synorim. But the google-drive link you provided seems wrong? Could you please give a valid link for downloading the mpc-dt4d dataset?

Thank you!

**Comment by tolgabirdal** [comment]
Thanks for your interest Fulin. MPC-DT4D dataset is from DeformingThings4D: https://github.com/rabbityl/DeformingThings4D. You can find the original form as well as the details there.

Cheers,

**Comment by heiwang1997** [comment]
Thanks @tolgabirdal for the explanation! @1939938853  You can also try this link: https://drive.google.com/file/d/1r9VFHIZcatSej6guY_hGoGjrNqbgazAz/view
